export default [
	{
		id: 1,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
	{
		id: 2,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
	{
		id: 3,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
	{
		id: 4,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
	{
		id: 5,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
	{
		id: 6,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
	{
		id: 7,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
	{
		id: 8,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
	{
		id: 9,
		nomeShopping: 'Nome Shopping',
		nomeFantasia: 'SIBERIAN E CRAWFORD',
		luc: 'SAM00202',
		vctBoleto: '23/06/2020',
		qtdNegativacoes: '06',
		qtdExcecoes: '02',
		justificativa: 'desc',
		numeroChamado: '123456',
		obs: 'ObsDesc',
	},
];
